#ifndef IMXVPUAPI2_IMX8M_HANTRO_H
#define IMXVPUAPI2_IMX8M_HANTRO_H

#include "imxvpuapi2.h"


typedef enum
{
	IMX_VPU_API_HANTRO_COLOR_FORMAT_YUV420_SEMI_PLANAR_4x4TILED_8BIT = (IMX_VPU_API_COLOR_FORMAT_HARDWARE_SPECIFIC + 0),
	IMX_VPU_API_HANTRO_COLOR_FORMAT_YUV420_SEMI_PLANAR_4x4TILED_10BIT,
	IMX_VPU_API_HANTRO_COLOR_FORMAT_YUV420_SEMI_PLANAR_8x4TILED_8BIT,
	IMX_VPU_API_HANTRO_COLOR_FORMAT_YUV420_SEMI_PLANAR_8x4TILED_10BIT
}
ImxVpuApiHantroColorFormat;

#define IMX_VPU_API_HARDWARE_TYPE_HANTRO  IMX_VPU_API_MAKE_FOURCC_UINT32('H','T','R','O')


#endif /* IMXVPUAPI2_IMX8M_HANTRO_H */
